# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
#     1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.


number1 = 1
number2 = 2
fibonacci = 0
sum = 2
print(number1)
print(number2)
while fibonacci < 4000000:
    fibonacci = number1 + number2
    number1 = number2
    number2 = fibonacci
    print(fibonacci)
    if fibonacci % 2 == 0:
        sum += fibonacci
print(sum)